// This file is automatically generated by qtc from "core.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates\core.qtpl:1
package templates

//line templates\core.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates\core.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates\core.qtpl:1
func StreamHead(qw422016 *qt422016.Writer, title string) {
	//line templates\core.qtpl:1
	qw422016.N().S(`
<html>
<head>
    <title>`)
	//line templates\core.qtpl:4
	qw422016.E().S(title)
	//line templates\core.qtpl:4
	qw422016.N().S(`</title>
    <link type="text/css" rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="/static/css/ripples.min.css">
    <link type="text/css" rel="stylesheet" href="/static/css/bootstrap-material-design.min.css">
    <link type="text/css" rel="stylesheet" href="/static/css/template.css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
</head>
<body>
`)
//line templates\core.qtpl:14
}

//line templates\core.qtpl:14
func WriteHead(qq422016 qtio422016.Writer, title string) {
	//line templates\core.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates\core.qtpl:14
	StreamHead(qw422016, title)
	//line templates\core.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line templates\core.qtpl:14
}

//line templates\core.qtpl:14
func Head(title string) string {
	//line templates\core.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates\core.qtpl:14
	WriteHead(qb422016, title)
	//line templates\core.qtpl:14
	qs422016 := string(qb422016.B)
	//line templates\core.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates\core.qtpl:14
	return qs422016
//line templates\core.qtpl:14
}

//line templates\core.qtpl:16
func StreamFooter(qw422016 *qt422016.Writer) {
	//line templates\core.qtpl:16
	qw422016.N().S(`
<div class="alert alert-success" style="display: none">
  <strong>Success!</strong> <em>Indicates a successful or positive action.</em>
</div>
<div class="alert alert-danger" style="display: none">
  <strong>Danger!</strong> <em>Indicates a dangerous or potentially negative action.</em>
</div>

<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/ripples.min.js"></script>
<script src="/static/js/material.min.js"></script>
<script src="/static/js/template.js"></script>
<script src="/static/js/jquery.maskedinput.min.js"></script>
<script>$.material.init();</script>
<script src="https://fezvrasta.github.io/snackbarjs/dist/snackbar.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/6.2.0/jquery.nouislider.min.js"></script>
<script src="/static/js/app.js"></script>
</body>
</html>
`)
//line templates\core.qtpl:35
}

//line templates\core.qtpl:35
func WriteFooter(qq422016 qtio422016.Writer) {
	//line templates\core.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates\core.qtpl:35
	StreamFooter(qw422016)
	//line templates\core.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line templates\core.qtpl:35
}

//line templates\core.qtpl:35
func Footer() string {
	//line templates\core.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates\core.qtpl:35
	WriteFooter(qb422016)
	//line templates\core.qtpl:35
	qs422016 := string(qb422016.B)
	//line templates\core.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates\core.qtpl:35
	return qs422016
//line templates\core.qtpl:35
}
