// This file is automatically generated by qtc from "login.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates\login.qtpl:1
package templates

//line templates\login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates\login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates\login.qtpl:1
func StreamLoginPage(qw422016 *qt422016.Writer) {
	//line templates\login.qtpl:1
	qw422016.N().S(`
`)
	//line templates\login.qtpl:2
	StreamHead(qw422016, "login")
	//line templates\login.qtpl:2
	qw422016.N().S(`
<div id="blurr">
    <div class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Testing system</a>
            </div>
        </div>
    </div>

    <form class="form-horizontal form-cont" action="/login/" method="post">
        <fieldset>
            <legend>Login</legend>
            <div class="form-group">
                <!--input type="text" name="login"-->
                <label for="inputLogin" class="col-md-2 control-label">Login</label>

                <div class="col-md-10">
                    <input type="login" name="login" class="form-control" id="inputLogin" >
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword" class="col-md-2 control-label">Password</label>

                <div class="col-md-10">
                    <input type="password" name="password" class="form-control" id="inputPassword">

                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 col-md-offset-2">
                    <button type="submit" class="btn btn-primary left">Submit</button>
                </div>
            </div>

        </fieldset>
    </form>

</div>
<div id="black-block"></div>
`)
	//line templates\login.qtpl:48
	StreamFooter(qw422016)
	//line templates\login.qtpl:48
	qw422016.N().S(`
`)
//line templates\login.qtpl:49
}

//line templates\login.qtpl:49
func WriteLoginPage(qq422016 qtio422016.Writer) {
	//line templates\login.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates\login.qtpl:49
	StreamLoginPage(qw422016)
	//line templates\login.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line templates\login.qtpl:49
}

//line templates\login.qtpl:49
func LoginPage() string {
	//line templates\login.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates\login.qtpl:49
	WriteLoginPage(qb422016)
	//line templates\login.qtpl:49
	qs422016 := string(qb422016.B)
	//line templates\login.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates\login.qtpl:49
	return qs422016
//line templates\login.qtpl:49
}
